# Generated by Django 5.0 on 2024-02-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_boardgame_comments_deal_room_topic_user_bio_user_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='purchases',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='user',
            name='sells',
            field=models.IntegerField(default=0),
        ),
    ]
