# Generated by Django 5.0 on 2024-02-18 14:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_boardgame_complexity_boardgame_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deal',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='duration',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(600), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='players',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='rank',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(5000), django.core.validators.MinValueValidator(1)]),
        ),
    ]
