# Generated by Django 5.0 on 2024-02-18 14:26

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_deal_options_alter_boardgame_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgame',
            name='price',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(100000000), django.core.validators.MinValueValidator(10000)]),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='rank',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5000), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='topics',
            field=models.ManyToManyField(blank=True, null=True, related_name='topics', to='base.topic'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='buyer',
            field=models.ManyToManyField(blank=True, null=True, related_name='buyer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deal',
            name='stock',
            field=models.ManyToManyField(blank=True, null=True, related_name='stock', to='base.boardgame'),
        ),
    ]
